---
- name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} git init"
  when:
    - stat_path.stat.exists | bool
    - not stat_git.stat.exists | bool
  # ignore_errors: true
  ansible.builtin.command:
    cmd: "git -C {{ repo.path }} init"

- name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} get path git status"
  register: stat_git
  ansible.builtin.stat:
    path: "{{ repo.path }}/.git"
