---
- name: "Run git config for {{ repo.name }}"
  when:
    - stat_git.stat.exists | bool
    - repo.configs is iterable
  loop: "{{ repo.configs | flatten }}"
  loop_control:
    loop_var: config
    label: "config: {{ config.name }}"
  community.general.git_config:
    name: "{{ config.name }}"
    value: "{{ config.value }}"
    state: "{{ config.state }}"
    scope: local
    repo: "{{ repo.path }}"

- name: "Set .gitignores for {{ repo.name }}"
  when: stat_path.stat.exists | bool
  ansible.builtin.copy:
    content: "{{ repo.ignores }}"
    dest: "{{ repo.path }}/.gitignore"
    owner: root
    group: root
    mode: "0644"
