---
# - name: "{{ repo.name }} git remote remove {{ remote.name }}"
#   ansible.builtin.shell:
#     cmd: 'git -C {{ repo.path }} remote remove {{ remote.name }} || echo 0'
#   when: remote.state == "absent"

# - name: "{{ repo.name }} git remote add {{ remote.name }} {{ remote.url }}"
#   ansible.builtin.shell:
#     cmd: 'git -C {{ repo.path }} remote add {{ remote.name }} {{ remote.url }} || echo 0'
#   when: remote.state == "present"

# - name: "{{ repo.name }} git remote add {{ remote.name }}"
- block:
    - name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} git remote remove {{ remote.name }} url"
      community.general.git_config:
        name: "remote.{{ remote.name }}.url"
        # value: "{{ remote.url }}"
        state: "absent"
        scope: local
        repo: "{{ repo.path }}"

    - name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} git remote remove {{ remote.name }} fetch settings"
      community.general.git_config:
        name: "remote.{{ remote.name }}.fetch"
        # value: "+refs/heads/*:refs/remotes/origin/*"
        state: "absent"
        scope: local
        repo: "{{ repo.path }}"
  when: remote.state == "absent"

# - name: "{{ repo.name }} git remote remove {{ remote.name }}"
- block:
    - name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} git remote add {{ remote.name }} url"
      community.general.git_config:
        name: "remote.{{ remote.name }}.url"
        value: "{{ remote.url }}"
        state: "present"
        scope: local
        repo: "{{ repo.path }}"

    - name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} git remote add {{ remote.name }} fetch settings"
      community.general.git_config:
        name: "remote.{{ remote.name }}.fetch"
        value: "+refs/heads/*:refs/remotes/{{ remote.name }}/*"
        state: "present"
        scope: local
        repo: "{{ repo.path }}"
  when: remote.state == "present"
