---
- name: "Run git push for {{ repo.name }}"
  ignore_errors: "{{ action.ignore_error | default('false') | bool }}"
  ansible.builtin.command:
    cmd: "git -C {{ repo.path }} push {{ action.extra_params | default('') }} {{ action.to }}"
