---
- name: "{{ item.name }} get path infos"
  stat:
    path: "{{ item.path }}"
  register: stat_path


- name: "{{ item.name }} get path git status"
  stat:
    path: "{{ item.path }}/.git"
  register: stat_git


- name: "{{ item.name }} start git init tasks"
  include_tasks:
    file: "tasks/sub-tasks/git_enable_init.yml"
  when: item.make_init | bool


- name: "{{ item.name }} start git config tasks"
  include_tasks:
    file: "tasks/sub-tasks/git_enable_configs.yml"
  when: item.make_conf_options | bool


- name: "{{ item.name }} start git remotes tasks"
  include_tasks:
    file: "tasks/sub-tasks/git_enable_remotes.yml"
  loop: "{{ item.remotes | flatten }}"
  loop_control:
    loop_var: remote
  when: 
    - stat_git.stat.exists | bool
    - item.remotes is iterable
    - item.make_conf_remotes | bool


- name: "{{ item.name }} start git actions tasks"
  include_tasks:
    file: "tasks/sub-tasks/git_enable_actions.yml"
  when: item.make_actions | bool
