---
- name: "{{ item.name }} git init"
  ansible.builtin.shell:
    cmd: "git -C {{ item.path }} init"
  when:
    - stat_path.stat.exists | bool
    - not stat_git.stat.exists | bool
  # ignore_errors: true

- name: "{{ item.name }} get path git status"
  ansible.builtin.stat:
    path: "{{ item.path }}/.git"
  register: stat_git
