---
- name: '[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} git commit "{{ action.message }}"'
  ansible.builtin.shell:
    # cmd: 'git -C {{ repo.path }} commit -m "{{ action.message }}" || true'
    # cmd: 'git -C {{ repo.path }} commit --allow-empty -m "{{ action.message }}" '
    cmd: 'git -C {{ repo.path }} commit -m "{{ action.message }}"'
    # cmd: 'git -C {{ repo.path }} diff-index --quiet HEAD  || git -C {{ repo.path }} commit -m "{{ action.message }}" '
  # ignore_errors: true
  ignore_errors: "{{ action.ignore_error | default('false') | bool }}"
  register: commit_output
  failed_when: >
                "nothing to commit, working tree clean" not in commit_output.stdout
                and
                commit_output.rc > 0
