---
- name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} get path infos"
  register: stat_path
  ansible.builtin.stat:
    path: "{{ repo.path }}"

- name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} get path git status"
  register: stat_git
  ansible.builtin.stat:
    path: "{{ repo.path }}/.git"

- name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} include git init tasks"
  when: repo.make_init | bool
  ansible.builtin.include_tasks:
    file: "tasks/sub-tasks/git_enable_init.yml"

- name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} include git config tasks"
  when: repo.make_conf_options | bool
  ansible.builtin.include_tasks:
    file: "tasks/sub-tasks/git_enable_configs.yml"

- name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} include git remotes tasks"
  when:
    - stat_git.stat.exists | bool
    - repo.remotes is iterable
    - repo.make_conf_remotes | bool
  loop: "{{ repo.remotes | flatten }}"
  loop_control:
    loop_var: remote
  ansible.builtin.include_tasks:
    file: "tasks/sub-tasks/git_enable_remotes.yml"

# - name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} include git submodules config tasks"
#   ansible.builtin.include_tasks:
#     file: "tasks/sub-tasks/git_enable_submodules_config.yml"
#   loop: "{{ repo.submodules | flatten }}"
#   loop_control:
#     loop_var: remote
#   when:
#     - stat_git.stat.exists | bool
#     - repo.submodules is iterable
#     - repo.make_submodules_conf | bool

# - name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} include git submodules actions tasks"
#   ansible.builtin.include_tasks:
#     file: "tasks/sub-tasks/git_enable_submodules_actions.yml"
#   loop: "{{ repo.submodules | flatten }}"
#   loop_control:
#     loop_var: remote
#   when:
#     - stat_git.stat.exists | bool
#     - repo.submodules is iterable
#     - repo.make_submodules_actions | bool

- name: "[{{ ansible_loop.index }}/{{ ansible_loop.length }}] {{ repo.name }} include git actions tasks"
  when: repo.make_actions | bool
  ansible.builtin.include_tasks:
    file: "tasks/sub-tasks/git_enable_actions.yml"
