---
- name: "Run git diff-index for {{ repo.name }}"
  ignore_errors: "{{ action.ignore_error | default('false') | bool }}"
  register: diff_output
  # failed_when: >
  #   "nothing to commit, working tree clean" not in commit_output.stdout
  #   and
  #   commit_output.rc > 0
  failed_when: diff_output.rc > 1
  ansible.builtin.command:
    cmd: 'git -C {{ repo.path }} diff-index --quiet HEAD'
    # cmd: 'git -C {{ repo.path }} commit -m "{{ action.message }}" || true'
    # cmd: 'git -C {{ repo.path }} commit --allow-empty -m "{{ action.message }}" '
    # cmd: 'git -C {{ repo.path }} diff-index --quiet HEAD  || git -C {{ repo.path }} commit -m "{{ action.message }}" '


- name: "Run git commit for {{ repo.name }}"
  ignore_errors: "{{ action.ignore_error | default('false') | bool }}"
  when:
    - diff_output is defined
    - diff_output.rc is defined 
    - diff_output.rc > 0
  register: commit_output
  # failed_when: >
  #   "nothing to commit, working tree clean" not in commit_output.stdout
  #   and
  #   commit_output.rc > 0
  # failed_when: commit_output.rc > 0
  ansible.builtin.command:
    cmd: 'git -C {{ repo.path }} commit {{ action.extra_params | default("") }} --message="{{ git_repos_commit_msg | default(action.message) }}"'
    # cmd: 'git -C {{ repo.path }} commit -m "{{ action.message }}" || true'
    # cmd: 'git -C {{ repo.path }} commit --allow-empty -m "{{ action.message }}" '
    # cmd: 'git -C {{ repo.path }} diff-index --quiet HEAD  || git -C {{ repo.path }} commit -m "{{ action.message }}" '
