---
- name: "Run git init for {{ repo.name }}"
  when:
    - stat_path.stat.exists | bool
    - not stat_git.stat.exists | bool
  # ignore_errors: true
  ansible.builtin.command:
    cmd: "git -C {{ repo.path }} init"

- name: "Get current git status in {{ repo.path }}"
  register: stat_git
  ansible.builtin.stat:
    path: "{{ repo.path }}/.git"
