---
- name: "Run git pull for {{ repo.name }}"
  ignore_errors: "{{ action.ignore_error | default('false') | bool }}"
  ansible.builtin.command:
    cmd: "git -C {{ repo.path }} pull {{ action.extra_params | default('') }} {{ action.from }}"
