---
- name: Install git package
  tags:
    - install
  when: git_repos_install_binary | bool
  ansible.builtin.package:
    name: git
    state: present


- name: Include tasks for active git repos
  tags:
    - present
  when:
    - git_repos is iterable
    - repo.state == "present"
  loop: "{{ git_repos | flatten }}"
  loop_control:
    loop_var: repo
    extended: true
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/git_enable.yml


- name: Include tasks for disabled git repos
  tags:
    - absent
  when:
    - git_repos is iterable
    - repo.state == "absent"
  loop: "{{ git_repos | flatten }}"
  loop_control:
    loop_var: repo
    extended: true
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/git_disable.yml
