---
- name: Install git
  ansible.builtin.package:
    name: git
    state: present
  when: git_repos_install_binary | bool

- name: Include tasks for active git repos
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/git_enable.yml
  loop: "{{ git_repos | flatten }}"
  loop_control:
    loop_var: repo
    extended: yes
  when: >
    git_repos is iterable
    and
    repo.state == "present"

- name: Include tasks for disabled git repos
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/git_disable.yml
  loop: "{{ git_repos | flatten }}"
  loop_control:
    loop_var: repo
    extended: yes
  when: >
    git_repos is iterable
    and
    repo.state == "absent"
